version: '3'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=CHANGE
      - POSTGRES_PASSWORD=CHANGE
      - POSTGRES_DB=orders_database
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgresql"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - order-network
  migrations:
    image: liquibase/liquibase:latest
    volumes:
      - ./services/order_service/migrations:/app
    command: --defaultsFile=/app/order.properties update
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - order-network
  order-service:
    container_name: "order-service"
    build:
      context: services/order_service
      dockerfile: internal/orders.dockerfile
    ports:
      - "8001:8001"
    depends_on:
      postgresql:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - order-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    networks:
      - order-network
  answer_engine_fastapi:
    container_name: "lessons-answer-engine"
    build:
      context: services/AnswerEngine
      dockerfile: src/bot.dockerfile
    ports:
      - "7090:7090"
    networks:
      - order-network

networks:
  order-network:
    name: "order-network"
