package custom_errors

import "errors"

var ErrorGetUser = errors.New("cannot get user")
var ErrGetOrder = errors.New("cannot get order")
var ErrResponseAlredyExist = errors.New("response already exist")
var ErrNotAllowed = errors.New("not allowed")
var ErrorInvalidToken = errors.New("invalid token")
var ErrorAlreadySetTutor = errors.New("tutor is already set on this order")
var ErrorSetStatus = errors.New("cannot set status")
var ErrorServiceError = errors.New("error with service")
var ErrorSelectTutor = errors.New("error with select tutor")
var ErrorGetResponse = errors.New("error with get response")
var ErrorBadStatus = errors.New("error bad status")
var ErrorNotActiveReview = errors.New("error not active review")
var ErrorNotFound = errors.New("not found")
var ErrorParams = errors.New("bad params")
var ErrorBanWords = errors.New("order contains ban words")
var ErrorCreateUser = errors.New("cannot create user")
var ErrorInvalidRole = errors.New("invalid role")
var UserNotFound = errors.New("user not found")
var ErrorWithCreate = errors.New("cannot create user")
var ErrorIncorrectRole = errors.New("incorrect role")
var ErrorAfterRowScan = errors.New("error after rows scan")
var ErrorCountLessZero = errors.New("count less than zero")
