openapi: 3.0.0
info:
  title: Order Service API
  description: API для управления заказами в приложении для репетиторов.
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Локальный сервер

paths:
  /orders:
    get:
      summary: Получить список всех заказов
      tags:
        - Заказы
      responses:
        '200':
          description: Успешный ответ с списком всех заказов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Создать новый заказ
      tags:
        - Заказы
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderInput'
      responses:
        '201':
          description: Заказ успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Некорректные данные

  /orders/{id}:
    get:
      summary: Получить информацию о заказе по ID
      tags:
        - Заказы
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Успешный ответ с данными о заказе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Заказ не найден
    put:
      summary: Обновить заказ по ID
      tags:
        - Заказы
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderInput'
      responses:
        '200':
          description: Заказ успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Некорректные данные
        '404':
          description: Заказ не найден
    delete:
      summary: Удалить заказ по ID
      tags:
        - Заказы
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Заказ успешно удален
        '404':
          description: Заказ не найден

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          description: Уникальный идентификатор заказа
        id_student:
          type: string
          description: Уникальный идентификатор студента
        grade:
          type: string
          description: Класс или уровень ученика (например, "8-й класс" или "Начальный уровень")
        subject:
          type: string
          description: Предмет, по которому требуется урок
        description:
          type: string
          description: Краткое описание заказа
        price_min:
          type: number
          format: float
          description: Минимальная цена за урок
        price_max:
          type: number
          format: float
          description: Максимальная цена за урок
        createdAt:
          type: string
          format: date-time
          description: Дата создания заказа
    OrderInput:
      type: object
      properties:
        id_student:
          type: string
          description: Уникальный идентификатор студента
        grade:
          type: string
          description: Класс или уровень ученика
        subject:
          type: string
          description: Предмет, по которому требуется урок
        description:
          type: string
          description: Краткое описание заказа
        price_min:
          type: number
          format: float
          description: Минимальная цена за урок
        price_max:
          type: number
          format: float
          description: Максимальная цена за урок
      required:
        - id_student
        - grade
        - subject
        - price_min
        - price_max
